x-app-env: &app-env
  environment:
    - NGINX_PORT=${NGINX_PORT:-80}
    - WEB_URL=${WEB_URL:-http://localhost}
    - DEBUG=${DEBUG:-0}
    - SENTRY_DSN=${SENTRY_DSN}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-"production"}
    - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS}
    # Gunicorn Workers
    - GUNICORN_WORKERS=${GUNICORN_WORKERS:-1}
    #DB SETTINGS
    - PGHOST=${PGHOST:-plane-db}
    - PGDATABASE=${PGDATABASE:-plane}
    - POSTGRES_USER=${POSTGRES_USER:-plane}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-plane}
    - POSTGRES_DB=${POSTGRES_DB:-plane}
    - POSTGRES_PORT=${POSTGRES_PORT:-5432}
    - PGDATA=${PGDATA:-/var/lib/postgresql/data}
    - DATABASE_URL=${DATABASE_URL:-postgresql://plane:plane@plane-db/plane}
    # REDIS SETTINGS
    - REDIS_HOST=${REDIS_HOST:-plane-redis}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}
    # Application secret
    - SECRET_KEY=${SECRET_KEY:-60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5}
    # DATA STORE SETTINGS
    - USE_MINIO=${USE_MINIO:-1}
    - AWS_REGION=${AWS_REGION:-""}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-"access-key"}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-"secret-key"}
    - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:-http://plane-minio:9000}
    - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-uploads}
    - MINIO_ROOT_USER=${MINIO_ROOT_USER:-"access-key"}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-"secret-key"}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    # Admin and Space URLs
    - ADMIN_BASE_URL=${ADMIN_BASE_URL}
    - SPACE_BASE_URL=${SPACE_BASE_URL}
    - APP_BASE_URL=${APP_BASE_URL}

services:
  web:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-frontend:${APP_RELEASE:-stable}
    networks:
      - traefik-service-net
      - plane-internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-service-net"
      - "traefik.http.services.web-plane.loadbalancer.server.port=3000"
      - "traefik.http.routers.plane.rule=Host(`plane.nkleinbaer.com`)"
      - "traefik.http.routers.plane.middlewares=traefikAuth@file, secHeaders@file"
      - "traefik.http.routers.plane.tls.certresolver=dnschallenge"
      - "traefik.http.routers.plane.entrypoints=web-secure"
      - "traefik.http.routers.plane.tls.domains[0].main=plane.nkleinbaer.com"
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: node web/server.js web
    deploy:
      replicas: ${WEB_REPLICAS:-1}
    depends_on:
      - api
      - worker

  space:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-space:${APP_RELEASE:-stable}
    networks:
      - traefik-service-net
      - plane-internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-service-net"
      - "traefik.http.services.space-plane.loadbalancer.server.port=3000"
      - "traefik.http.routers.plane-space.rule=Host(`plane.nkleinbaer.com`) && PathPrefix(`/spaces`)"
      - "traefik.http.routers.plane-space.middlewares=traefikAuth@file, secHeaders@file"
      - "traefik.http.routers.plane-space.tls.certresolver=dnschallenge"
      - "traefik.http.routers.plane-space.entrypoints=web-secure"
      - "traefik.http.routers.plane-space.tls.domains[0].main=plane.nkleinbaer.com"
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: node space/server.js space
    deploy:
      replicas: ${SPACE_REPLICAS:-1}
    depends_on:
      - api
      - worker
      - web

  admin:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-admin:${APP_RELEASE:-stable}
    networks:
      - traefik-service-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-service-net"
      - "traefik.http.services.admin-plane.loadbalancer.server.port=3000"
      - "traefik.http.routers.plane-admin.rule=Host(`plane.nkleinbaer.com`) && PathPrefix(`/god-mode`)"
      - "traefik.http.routers.plane-admin.middlewares=traefikAuth@file, secHeaders@file"
      - "traefik.http.routers.plane-admin.tls.certresolver=dnschallenge"
      - "traefik.http.routers.plane-admin.entrypoints=web-secure"
      - "traefik.http.routers.plane-admin.tls.domains[0].main=plane.nkleinbaer.com"
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: node admin/server.js admin
    deploy:
      replicas: ${ADMIN_REPLICAS:-1}
    depends_on:
      - api
      - web

  api:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    networks:
      - traefik-service-net
      - plane-internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-service-net"
      - "traefik.http.services.api-plane.loadbalancer.server.port=8000"
      - "traefik.http.routers.plane-api.rule=Host(`plane.nkleinbaer.com`) && (PathPrefix(`/api`) || PathPrefix(`/auth`))"
      - "traefik.http.routers.plane-api.middlewares=traefikAuth@file, secHeaders@file"
      - "traefik.http.routers.plane-api.tls.certresolver=dnschallenge"
      - "traefik.http.routers.plane-api.entrypoints=web-secure"
      - "traefik.http.routers.plane-api.tls.domains[0].main=plane.nkleinbaer.com"
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-api.sh
    deploy:
      replicas: ${API_REPLICAS:-1}
    volumes:
      - /mnt/data/plane/logs_api:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    networks:
      - plane-internal-net
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-worker.sh
    volumes:
      - /mnt/data/plane/logs_worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    networks:
      - plane-internal-net
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-beat.sh
    volumes:
      - /mnt/data/plane/logs_beat-worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    <<: *app-env
    image: ${DOCKERHUB_USER:-makeplane}/plane-backend:${APP_RELEASE:-stable}
    networks:
      - plane-internal-net
    platform: ${DOCKER_PLATFORM:-}
    pull_policy: ${PULL_POLICY:-always}
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    volumes:
      - /mnt/data/plane/logs_migrator:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  plane-db:
    <<: *app-env
    image: postgres:15.5-alpine
    networks:
      - plane-internal-net
    pull_policy: if_not_present
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    volumes:
      - /mnt/data/plane/pgdata:/var/lib/postgresql/data

  plane-redis:
    <<: *app-env
    image: valkey/valkey:7.2.5-alpine
    networks:
      - plane-internal-net
    pull_policy: if_not_present
    restart: unless-stopped
    volumes:
      - /mnt/data/plane/redisdata:/data

  plane-minio:
    <<: *app-env
    image: minio/minio:latest
    networks:
      - traefik-service-net
      - plane-internal-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-service-net"
      - "traefik.http.services.plane-minio-plane.loadbalancer.server.port=9000"
      - "traefik.http.routers.plane-minio.rule=(Host(`plane.nkleinbaer.com`) && PathPrefix(`/uploads`)) || Host(`plane-minio.local`)"
      - "traefik.http.routers.plane-minio.middlewares=traefikAuth@file, secHeaders@file"
      - "traefik.http.routers.plane-minio.tls.certresolver=dnschallenge"
      - "traefik.http.routers.plane-minio.entrypoints=web-secure"
      - "traefik.http.routers.plane-minio.tls.domains[0].main=plane.nkleinbaer.com"
    pull_policy: if_not_present
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - /mnt/data/plane/uploads:/export

networks:
  traefik-service-net:
    external: true
  plane-internal-net:
    name: z-plane-internal-net
    internal: true
