services:
  goesproc:
    container_name: goestools-goesproc
    image: goestools
    volumes:
      - /mnt/data/goes:/data
    command:
      - 'goesproc'
      - '-c'
      - '/usr/share/goestools/goesproc-goesr.conf'
      - '-m'
      - 'packet' 
      - '--subscribe' 
      - 'tcp://host.docker.internal:5004'
      - '--out' 
      - '/data'
    extra_hosts:
      - "host.docker.internal:host-gateway"

