- name: Install and configure Docker
  hosts: homelab
  tags:
    - docker
  vars:
    docker_users:
      - nick
  roles:
    - geerlingguy.docker
  become: true

- name: Configure storage
  hosts: homelab
  tags:
    - storage
  become: true
  tasks:
    - name: Create mountpoint
      ansible.builtin.command: mkdir -p /mnt/data
    - name: Update fstab
      lineinfile:
         path: '/etc/fstab'
         line: "UUID=4c8d87c7-ab3b-4d2c-be46-aebfda67f3ca	/mnt/data	ext4	defaults,noatime,nofail	0	2"
    - name: Mount 
      ansible.builtin.command: mount -a 
    - name: Reload systemd 
      ansible.builtin.command: systemctl daemon-reload

- name: Pull IaC
  hosts: homelab
  tags:
    iac
  tasks:
    - name: Delete existing repo
      become: true
      ansible.builtin.file:
        path: /home/nick/homelab
        state: absent
    - name: Pull repo
      ansible.builtin.git:
        repo: https://github.com/nkleinbaer/homelab
        dest: ~/homelab
  
- name: Configure mDNS
  hosts: homelab
  tags:
    - mdns
  tasks:
    - name: Install Avahi utils
      become: true
      ansible.builtin.package:
        name: avahi-utils
        state: present
    - name: Configure mDNS publishing service
      become: true
      ansible.builtin.script: ../mdns/configure-mdns.sh

- name: Set up traefik
  hosts: homelab
  tags:
    - traefik
  tasks:
    - name: Bring up stack
      ansible.builtin.command: docker compose -f /home/nick/homelab/traefik/docker-compose.yaml up -d

- name: Set up monitoring
  hosts: homelab
  tags:
    - monitoring
  tasks:
    - name: Set up data dirs
      ansible.builtin.script: ../monitoring/configure-monitoring.sh
    - name: Bring up stack
      ansible.builtin.command: docker compose -f /home/nick/homelab/monitoring/docker-compose.yml up -d


- name: Set up plane
  hosts: homelab
  tags:
    - plane
  tasks:
    - name: Bring up stack
      ansible.builtin.command: docker compose -f /home/nick/homelab/plane/docker-compose.yaml up -d

- name: Set up goestools
  hosts: homelab
  tags:
    - goestools
  tasks:
    - name: Blacklist DVB Driver
      become: true
      lineinfile:
        create: true
        path: '/etc/modprobe.d/blacklist-dvb_usb_rtl28xxu.conf'
        line: 'blacklist dvb_usb_rtl28xxu'
      register: blacklist
    - name: Reboot
      become: true
      when: blacklist.changed
      ansible.builtin.reboot:
    - name: Bring up stack
      ansible.builtin.command: docker compose -f /home/nick/homelab/goestools/docker-compose.yaml up -d

- name: Setup rclone
  hosts: homelab
  tags:
    - rclone
  vars_files:
    - secrets.yaml
  tasks:
    - name: Check for rclone command
      shell: which rclone >/dev/null 2>&1
      register: installed
      ignore_errors: yes
    - block:
        - name: Download rclone installer
          get_url:
            url: https://rclone.org/install.sh
            dest: /tmp/install-rclone.sh
            mode: 777
            force: true
        - name: Insall rclone
          become: true
          shell: /tmp/install-rclone.sh
        - name: Remove rclone installer
          file:
            path: /tmp/install-rclone.sh
            state: absent
      when: installed.rc != 0
    - name: Upload rclone config
      ansible.builtin.copy:
        src: ../goestools/rclone.conf
        dest: /home/nick/.config/rclone/rclone.conf
    - name: Add secrets to rclone config
      no_log: true
      community.general.ini_file:
        path: /home/nick/.config/rclone/rclone.conf
        section: pixeltraphouse
        option: '{{ item.key }}'
        value: '{{ item.value}}'
      loop: "{{ lookup('dict', data) }}"
    - name: Install rsyslog
      package:
        name: rsyslog 
        state: present
    - name: Setup cron job
      become: true
      ansible.builtin.cron:
        name: "Sync goes data to s3"
        minute: "*/5"
        job: "rclone move -vvv --delete-empty-src-dirs --config /home/nick/.config/rclone/rclone.conf /mnt/data/goes pixeltraphouse:pixeltraphouse/goes"
